config/routes.rb
Rails.application.routes.draw do

  root 'conversations#index'

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id

  scope :between, -> (sender_id, receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
  end

  def recipient(current_user)
    self.sender_id == current_user.id ? self.receiver : self.sender
  end

  def unread_message_count(current_user)
    self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def time
    created_at.strftime("%d/%m/%y at %l:%M %p")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password_confirmation, presence: true

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authenticate
    unless logged_in?
      flash[:error] = "You must be logged in to do that!"
      redirect_to login_path
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate

  def index
    @conversations = Conversation.where("sender_id = ? OR receiver_id = ?", current_user.id, current_user.id)
    @users = User.where.not(id: current_user.id)
  end

  def create
    if Conversation.between(params[:sender_id], params[:receiver_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:receiver_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    redirect_to conversation_messages_path(@conversation)
  end

  private
    def conversation_params
      params.permit(:sender_id, :receiver_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @conversation.messages.where("user_id != ? AND read = ?", current_user.id, false).update_all(read: true)
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    @message.user = current_user

    if @message.save
      ActionCable.server.broadcast "messages", { conversation_id: @conversation.id }
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private
    def message_params
      params.require(:message).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome back!"
    else
      flash.now.alert = "Invalid login credentials."
      render "new"
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Thanks for registering!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/views/application/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <a class="navbar-brand" href="/">Inbox</a>
    <div class="pull-right">
      <% if logged_in? %>
        <%= link_to 'Logout', logout_path, method: :delete, class: 'text-muted' %>
        <%= image_tag current_user.image.thumb, class: 'user-img', alt: current_user.username %>
      <% end %>
    </div>
  </div>
</nav>

app/views/application/_notices.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<% if alert %>
  <div class="alert alert-danger"><%= alert %></div>
<% end %>

app/views/conversations/index.html.erb
<div class="row">
  <div class="col-md-8">
    <ul class="list-group">
      <% @conversations.each do |conversation| %>
        <li class="list-group-item" data-conversation-id="<%= conversation.id %>">
          <%= link_to conversation.recipient(current_user).username, conversation_messages_path(conversation) %>
          <% if !conversation.unread_message_count(current_user).zero? %>
            <span class="badge"><%= conversation.unread_message_count(current_user) %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-4">
    <div class="form-group">
      <input id="search" placeholder="Search" class="form-control">
    </div>
    <ul id="users" class="list-group">
      <% @users.each do |user| %>
        <li class="list-group-item" data-searchstring="<%= user.username %> <%= user.name %>">
          <%= link_to user.username, conversations_path(sender_id: current_user.id, receiver_id: user.id), method: :post %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Conversations</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= action_cable_meta_tag %>
  </head>

  <body>
    <%= render "header" %>
    <main class="container">
      <%= render "notices" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/index.html.erb
<div id="messages">
  <% @conversation.messages.each do |message| %>
    <% if message.body %>
      <div class="media">
        <div class="media-left">
          <%= image_tag message.user.image.thumb, class: "media-object user-img", alt: message.user.username %>
        </div>
        <div class="media-body">
          <h5 class="media-heading"><%= message.user.username %> <small class="text-muted"><%= message.time %></small></h5>
          <p><%= message.body %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= form_for [@conversation, @message] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, autofocus: true, placeholder: "Your message", class: "form-control", rows: 5 %>
  </div>

  <%= f.submit "Send", class: "btn btn-primary pull-right" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user, url: register_path do |f| %>
  <% if @user.errors.any? %>
    <% for message in @user.errors.full_messages %>
      <div class="alert alert-danger" role="alert"><%= message %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Register", class: "btn btn-primary pull-right" %>
<% end %>